{
 "title": "Node Servers State",
 "tags": [ "node_exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Group",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU USage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Usage CPU on {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_MemFree_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_Cached_bytes{job=~\"$job\", instance=~\"$instance\"} - node_memory_Buffers_bytes{job=~\"$job\", instance=~\"$instance\"}) / (node_memory_MemTotal_bytes{job=~\"$job\", instance=~\"$instance\"}) * 100) by (instance)",
     "legendFormat": "Usage Memory on {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{job=~\"$job\", instance=~\"$instance\", mountpoint=~\"/.*\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev\"} - node_filesystem_free_bytes{job=~\"$job\", instance=~\"$instance\", mountpoint=~\"/.*\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev\"}) / node_filesystem_size_bytes{job=~\"$job\", instance=~\"$instance\", mountpoint=~\"/.*\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev\"} * 100) by (mountpoint,instance)",
     "legendFormat": "Usage disk space in {{mountpoint}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[5m])) + sum by (instance) (irate(node_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Network usage on {{instance}}"
    }
   ]
  }
 ]
}